version: '3'

services:
  api:
    build:
      context: ./api
    environment:
      - DB_HOST=db                # Имя хоста должно быть 'db'
      - DB_PORT=5432              # Порт подключения внутри контейнера — 5432
      - DB_USER=postgres
      - DB_PASSWORD=nastyad20
      - DB_NAME=areal_hr_test_db
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nastyad20
      POSTGRES_DB: areal_hr_test_db
    ports:
      - "5433:5432" # Внутри контейнера порт остается 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
